### ISSUE TITLE
TC Cabinet not repairing all items

### ISSUE THREAD

**Issue by c1ph3r88** [PeladorRW/ChargedGear#1]
I currently have two items that the cabinets are not repairing.  They are:

- Synthamide Duster (Synthamide provide from Rimefeller)
- Plainleather Parka

I'm not seeing any error messages in the logs indicating anything so I'm unsure what the issue might be.

https://i.imgur.com/KQzGfmr.png
https://i.imgur.com/oTWIoW6.png

**Comment by PeladorRW** [comment]
Your aware that the toolbox will attempt to repair a percentage of the max hit points (configurable in mod options) every IG hour. The toolboxes also need to be powered and not broken down, but from all appearances, this doesn't seem to be the issue.

**Comment by c1ph3r88** [comment]
Correct.  I verified that other items would repair with no issue.  Also had the issue with a synthamide cowboy hat.

**Comment by PeladorRW** [comment]
I've been unable to reproduce the problem when testing on a plainleather parka. It was repaired.

**Comment by c1ph3r88** [comment]
Yeah it's inconsistent on my side.  Now nothing is repairing.  I'm assuming a mod conflict.  If I find I'll let you know.

**Comment by PeladorRW** [comment]
Think i found the problem, can you restest plz.

**Comment by c1ph3r88** [comment]
It seems to be fixed.  Damaged a bunch of items and they all repaired without issue.  Thanks!
